
spring:
    datasource:
        url: "jdbc:h2:mem:ecommerce"
        driverClassName: "org.h2.Driver"
        username: "sa"
        password: "123456"
    jpa:
        database-platform: "org.hibernate.dialect.H2Dialect"
        hibernate:
           ddl-auto: update
        show-sql: true
      

